-- **NOTE** This is an autogenerated file.
-- Do Not modify
SCIENCE_COLOR = {}

SCIENCE_COLOR["automation-science-pack"] = { r = 237, g = 64, b = 64, a = 255 }
SCIENCE_COLOR["chemical-science-pack"] = { r = 82, g = 236, b = 243, a = 255 }
SCIENCE_COLOR["logistic-science-pack"] = { r = 84, g = 241, b = 96, a = 255 }
SCIENCE_COLOR["metallurgic-science-pack"] = { r = 255, g = 172, b = 64, a = 255 }
SCIENCE_COLOR["military-science-pack"] = { r = 149, g = 155, b = 177, a = 255 }
SCIENCE_COLOR["production-science-pack"] = { r = 219, g = 61, b = 239, a = 255 }
SCIENCE_COLOR["utility-science-pack"] = { r = 246, g = 237, b = 93, a = 255 }
